/** Canonical app routes — marketing site vs authenticated workspace. */
export const routes = {
  home: '/',
  login: '/login',
  app: '/app',
  news: '/app/news',
  drafts: '/app/drafts',
  draft: (id: string) => `/app/drafts/${id}`,
  capture: '/app/capture',
  sources: '/app/sources',
  brand: '/app/brand',
  brandOnboarding: '/app/brand/onboarding',
  brandDashboard: '/app/brand/intelligence',
  learning: '/app/learning',
  prompts: '/app/prompts',
  jobs: '/app/jobs',
  analytics: '/app/analytics',
  providers: '/app/providers',
  settings: '/app/settings',
  ideas: '/app/ideas',
  plan: '/app/plan',
  toPost: '/app/to-post',
  generation: '/app/generation',
  images: '/app/images',
  typography: '/app/typography',
  carousels: '/app/carousels',
  review: '/app/review',
} as const;
