"""Brand Intelligence ports — no ORM / vendor SDKs."""

from __future__ import annotations

import uuid
from typing import Any, Protocol

from app.modules.brand_intelligence.domain.models import (
    BrandCompletenessReport,
    BrandHealthReport,
    BrandImport,
    BrandImportJob,
    BrandMemory,
    BrandMemoryDraft,
    BrandMemoryReview,
    BrandMemoryVersion,
    BrandPersona,
    BrandProfile,
    BrandRecommendation,
    BrowserSessionRecord,
    CanonicalBrandObject,
    LogoAssetSet,
    NeverSayPolicy,
)


class BrandProfileRepository(Protocol):
    async def list_for_org(self, org_id: uuid.UUID) -> list[BrandProfile]: ...
    async def get(self, org_id: uuid.UUID, profile_id: uuid.UUID) -> BrandProfile | None: ...
    async def get_default(self, org_id: uuid.UUID) -> BrandProfile | None: ...
    async def create(self, profile: BrandProfile) -> BrandProfile: ...
    async def update(self, profile: BrandProfile) -> BrandProfile: ...
    async def ensure_default_corporate(self, org_id: uuid.UUID) -> BrandProfile: ...


class BrandPersonaRepository(Protocol):
    async def list_for_profile(self, org_id: uuid.UUID, profile_id: uuid.UUID) -> list[BrandPersona]: ...
    async def upsert(self, persona: BrandPersona) -> BrandPersona: ...


class NeverSayRepository(Protocol):
    async def get(self, org_id: uuid.UUID, profile_id: uuid.UUID) -> NeverSayPolicy | None: ...
    async def upsert(self, policy: NeverSayPolicy) -> NeverSayPolicy: ...


class BrandImportRepository(Protocol):
    async def create(self, row: BrandImport) -> BrandImport: ...
    async def get(self, org_id: uuid.UUID, import_id: uuid.UUID) -> BrandImport | None: ...
    async def update(self, row: BrandImport) -> BrandImport: ...
    async def delete(self, org_id: uuid.UUID, import_id: uuid.UUID) -> None: ...


class BrandImportJobRepository(Protocol):
    async def create(self, row: BrandImportJob) -> BrandImportJob: ...
    async def get(self, org_id: uuid.UUID, job_row_id: uuid.UUID) -> BrandImportJob | None: ...
    async def get_by_job_id(self, org_id: uuid.UUID, job_id: uuid.UUID) -> BrandImportJob | None: ...
    async def update(self, row: BrandImportJob) -> BrandImportJob: ...


class CanonicalObjectRepository(Protocol):
    async def bulk_upsert(self, objects: list[CanonicalBrandObject]) -> int: ...
    async def list_for_import(self, org_id: uuid.UUID, import_id: uuid.UUID) -> list[CanonicalBrandObject]: ...


class BrandMemoryRepository(Protocol):
    async def get_active(self, org_id: uuid.UUID, profile_id: uuid.UUID) -> BrandMemory | None: ...
    async def get(self, org_id: uuid.UUID, memory_id: uuid.UUID) -> BrandMemory | None: ...
    async def save(self, memory: BrandMemory) -> BrandMemory: ...
    async def list_versions(self, org_id: uuid.UUID, memory_id: uuid.UUID) -> list[BrandMemoryVersion]: ...
    async def save_version(self, version: BrandMemoryVersion) -> BrandMemoryVersion: ...
    async def get_version(self, org_id: uuid.UUID, memory_id: uuid.UUID, version_no: int) -> BrandMemoryVersion | None: ...


class BrandReviewRepository(Protocol):
    async def get_open(self, org_id: uuid.UUID, memory_id: uuid.UUID) -> BrandMemoryReview | None: ...
    async def save(self, review: BrandMemoryReview) -> BrandMemoryReview: ...


class LogoAssetRepository(Protocol):
    async def get(self, org_id: uuid.UUID, profile_id: uuid.UUID) -> LogoAssetSet | None: ...
    async def upsert(self, logo_set: LogoAssetSet) -> LogoAssetSet: ...


class BrowserSessionStore(Protocol):
    async def load(self, org_id: uuid.UUID, provider: str) -> BrowserSessionRecord | None: ...
    async def save(self, record: BrowserSessionRecord) -> BrowserSessionRecord: ...
    async def revoke(self, org_id: uuid.UUID, provider: str) -> None: ...


class BrandSourceConnector(Protocol):
    source_type: str

    async def fetch(self, config: dict[str, Any], session_state: bytes | None = None) -> list[CanonicalBrandObject]: ...


class CrawlerPort(Protocol):
    async def crawl(self, seed_url: str, max_pages: int = 20) -> list[dict[str, Any]]: ...


class OcrProvider(Protocol):
    async def extract(self, storage_key: str, content_type: str | None = None) -> dict[str, Any]: ...


class VisionAnalyzer(Protocol):
    async def analyze(self, storage_key: str) -> dict[str, Any]: ...


class WritingAnalyzer(Protocol):
    async def analyze(self, objects: list[CanonicalBrandObject]) -> dict[str, Any]: ...


class TopicAnalyzer(Protocol):
    async def analyze(self, objects: list[CanonicalBrandObject]) -> list[dict[str, Any]]: ...


class VocabularyAnalyzer(Protocol):
    async def analyze(self, objects: list[CanonicalBrandObject]) -> dict[str, Any]: ...


class HookAnalyzer(Protocol):
    async def analyze(self, objects: list[CanonicalBrandObject]) -> list[dict[str, Any]]: ...


class CtaAnalyzer(Protocol):
    async def analyze(self, objects: list[CanonicalBrandObject]) -> list[dict[str, Any]]: ...


class EngagementAnalyzer(Protocol):
    async def analyze(self, objects: list[CanonicalBrandObject]) -> dict[str, Any]: ...


class SemanticMergeEngine(Protocol):
    def merge(
        self,
        objects: list[CanonicalBrandObject],
        analyses: dict[str, Any],
        org_id: uuid.UUID,
        profile_id: uuid.UUID,
    ) -> BrandMemoryDraft: ...


class CompletenessEngine(Protocol):
    def score(self, draft: BrandMemoryDraft, source_mix: dict[str, Any]) -> BrandCompletenessReport: ...


class HealthEngine(Protocol):
    def evaluate(self, draft: BrandMemoryDraft, completeness: BrandCompletenessReport) -> BrandHealthReport: ...


class RecommendationEngine(Protocol):
    def recommend(
        self,
        draft: BrandMemoryDraft,
        completeness: BrandCompletenessReport,
        health: BrandHealthReport,
    ) -> list[BrandRecommendation]: ...


class BrandKnowledgeProjector(Protocol):
    async def project(self, memory: BrandMemory) -> None: ...
    async def index_vectors(self, memory: BrandMemory) -> int: ...
